service: aws-basic-serverless-framework

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-1
  deploymentBucket:
    name: aws-basic-serverless-framework-developer



functions:
  hello:
    handler: src/handler.generateRandomNumber
